-- MAKERS
SELECT CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS NAME, M.HANDLE, M.EMAIL, M.PHONE
FROM MAKERS AS M;

-- RECIPIENTS
SELECT CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS NAME, R.HANDLE, R.EMAIL, R.PHONE
FROM RECIPIENTS AS R;

-- BOUQUETS
SELECT FB.BOUQUET_ID, B.NAME AS BOUQUET, B.DESCRIPTION,
    F.FLOWER_ID, F.NAME as FLOWER,
    CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
    CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM FLOWERS_BOUQUETS AS FB
    LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
    LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY BOUQUET_ID;

-- FLOWERS
SELECT F.FLOWER_ID, F.NAME, F.MEANING, C.COLOR FROM FLOWERS AS F
LEFT JOIN COLORS AS C
    ON C.COLOR_ID = F.COLOR_ID;

INSERT INTO FLOWERS (NAME, MEANING, COLOR_ID)
VALUES (in_flower_name, in_flower_meaning, in_color_id );

UPDATE FLOWERS AS F
SET F.NAME=in_flower_name, F.MEANING=in_flower_meaning, F.COLOR_ID = in_color_id
WHERE F.FLOWER_ID=in_flower_id;

DELETE FROM `FLOWERS` WHERE FLOWER_ID = in_flower_id;

-- BOUQUETS - updated fields
-- FOOD_ITEMS_ORDERS - previous fields
SELECT ORDERS.ORDER_ID, FOOD_ITEMS.FOOD_ITEM_ID, FOOD_ITEMS.NAME, CUSTOMERS.FIRST_NAME, CUSTOMERS.LAST_NAME FROM FOOD_ITEMS_ORDERS
LEFT JOIN FOOD_ITEMS ON FOOD_ITEMS_ORDERS.FOOD_ITEM_ID = FOOD_ITEMS.FOOD_ITEM_ID
LEFT JOIN ORDERS ON FOOD_ITEMS_ORDERS.ORDER_ID = ORDERS.ORDER_ID
LEFT JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

INSERT INTO FOOD_ITEMS_ORDERS (FOOD_ITEM_ID, ORDER_ID) VALUES (:FOOD_ITEM_ID, :ORDER_ID);

UPDATE FOOD_ITEMS_ORDERS SET FOOD_ITEM_ID=:FOOD_ITEM_ID, ORDER_ID=:ORDER_ID WHERE FOOD_ITEM_ID=:FOOD_ITEM_ID;
UPDATE FOOD_ITEMS_ORDERS SET FOOD_ITEM_ID=:FOOD_ITEM_ID, ORDER_ID=:ORDER_ID WHERE ORDER_ID=:ORDER_ID;

-- Since the relationship requires a join, deleting a food item
-- deletes all orders depending on/containing that food item
-- deleting from FOOD_ITEMS_ORDERS is handled by the cascade,
-- but since ORDERS is not directly related to FOOD_ITEMS,
-- deleting from ORDERS happens explicitly when a FOOD_ITEM is deleted
-- if that ORDER contains that food item

-- Deleting a FOOD_ITEM results in deleting that item from FOOD_ITEMS_ORDERS by CASCADE
-- and explicitly from the ORDERS table via a JOIN involving the intersection table.
-- Citation for the syntax for the DELETE with JOIN. Date: 3/7/2026
-- Developed with reference to:
-- Source URL: https://stackoverflow.com/questions/2763206/deleting-rows-with-mysql-left-join
DELETE `FOOD_ITEMS_ORDERS`, `ORDERS` FROM ORDERS
    LEFT JOIN FOOD_ITEMS_ORDERS ON FOOD_ITEMS_ORDERS.ORDER_ID = ORDERS.ORDER_ID
    WHERE FOOD_ITEMS_ORDERS.FOOD_ITEM_ID = :FOOD_ITEM_ID_FROM_FORM;