--This work is original

-- MAKERS
SELECT CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS NAME, M.HANDLE, M.EMAIL, M.PHONE
FROM MAKERS AS M;

-- RECIPIENTS
SELECT CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS NAME, R.HANDLE, R.EMAIL, R.PHONE
FROM RECIPIENTS AS R;

-- COLORS
SELECT * FROM COLORS;

-- FLOWERS
SELECT F.FLOWER_ID, F.NAME, F.MEANING, C.COLOR FROM FLOWERS AS F
LEFT JOIN COLORS AS C
    ON C.COLOR_ID = F.COLOR_ID;

INSERT INTO FLOWERS (NAME, MEANING, COLOR_ID)
VALUES (in_flower_name, in_flower_meaning, in_color_id );

UPDATE FLOWERS AS F
SET F.NAME=in_flower_name, F.MEANING=in_flower_meaning, F.COLOR_ID = in_color_id
WHERE F.FLOWER_ID=in_flower_id;

DELETE FROM `FLOWERS` WHERE FLOWER_ID = in_flower_id;

-- FLOWERS_BOUQUETS
SELECT CONCAT(TRIM(C.COLOR), ' ', TRIM(F.NAME)) AS FLOWER,
    FB.FLOWER_ID, B.BOUQUET_ID, B.NAME AS BOUQUET
FROM FLOWERS_BOUQUETS AS FB
    LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN COLORS AS C ON C.COLOR_ID = F.COLOR_ID
ORDER BY B.BOUQUET_ID;
-- SELECT CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
--     B.NAME AS BOUQUET, FB.BOUQUET_ID, FB.FLOWER_ID, F.NAME AS FLOWER,
--     C.COLOR,
--     CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
-- FROM FLOWERS_BOUQUETS AS FB
--     LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
--     LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
--     LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
--     LEFT JOIN COLORS AS C ON C.COLOR_ID = F.COLOR_ID
--     LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
-- ORDER BY FB.BOUQUET_ID, FB.FLOWER_ID;

-- BOUQUETS
SELECT B.BOUQUET_ID, B.NAME AS BOUQUET, B.DESCRIPTION,
    CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
    CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM BOUQUETS AS B
    LEFT JOIN FLOWERS_BOUQUETS AS FB ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
    LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY B.BOUQUET_ID;



INSERT INTO BOUQUETS (NAME, DESCRIPTION, MAKER_ID, RECIPIENT_ID)
VALUES (in_bouquet_name, in_bouquet_description,
    in_maker_id, in_recipient_id );

UPDATE BOUQUETS AS B
SET B.NAME=in_bouquet_name, B.DESCRIPTION=in_bouquet_description,
    B.MAKER_ID=in_maker_id, B.RECIPIENT_ID=in_recipient_id
WHERE B.BOUQUET_ID=in_bouquet_id;

DELETE FROM BOUQUETS WHERE BOUQUET_ID = in_bouquet_id;