-- MAKERS
SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, ADDRESS, EMAIL 
FROM CUSTOMERS;

-- RECIPIENTS
SELECT RESTAURANT_ID, RATING, NAME, PHONE_NUMBER, ADDRESS, EMAIL 
FROM RESTAURANTS;

-- ORDERS
SELECT ORDERS.ORDER_ID, ORDER_DATE, CUSTOMERS.FIRST_NAME, CUSTOMERS.LAST_NAME,
RESTAURANTS.NAME, FOOD_ITEMS.NAME, FOOD_ITEMS.PRICE
FROM ORDERS
LEFT JOIN FOOD_ITEMS_ORDERS 
ON ORDERS.ORDER_ID = FOOD_ITEMS_ORDERS.ORDER_ID
LEFT JOIN FOOD_ITEMS 
ON FOOD_ITEMS.FOOD_ITEM_ID = FOOD_ITEMS_ORDERS.FOOD_ITEM_ID
LEFT JOIN RESTAURANTS 
ON FOOD_ITEMS.RESTAURANT_ID = RESTAURANTS.RESTAURANT_ID
LEFT JOIN CUSTOMERS 
ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

-- FOOD_ITEMS
SELECT FOOD_ITEMS.FOOD_ITEM_ID, RESTAURANTS.NAME, FOOD_ITEMS.NAME, FOOD_ITEMS.PRICE
FROM FOOD_ITEMS 
LEFT JOIN RESTAURANTS 
ON RESTAURANTS.RESTAURANT_ID = FOOD_ITEMS.RESTAURANT_ID;

INSERT INTO FOOD_ITEMS (RESTAURANT_ID, NAME, PRICE) VALUES (:RESTAURANT_ID, :NAME, :PRICE);

UPDATE FOOD_ITEMS SET RESTAURANT_ID=:RESTAURANT_ID, FOOD_ITEM_ID=:FOOD_ITEM_ID,
NAME=:NAME, PRICE=:PRICE 
WHERE FOOD_ITEM_ID=:FOOD_ITEM_ID_TO_UPDATE;

DELETE FROM FOOD_ITEMS WHERE FOOD_ITEM_ID = :FOOD_ITEM_ID_FROM_FORM;

-- FOOD_ITEMS_ORDERS
SELECT ORDERS.ORDER_ID, FOOD_ITEMS.FOOD_ITEM_ID, FOOD_ITEMS.NAME, CUSTOMERS.FIRST_NAME, CUSTOMERS.LAST_NAME FROM FOOD_ITEMS_ORDERS
LEFT JOIN FOOD_ITEMS ON FOOD_ITEMS_ORDERS.FOOD_ITEM_ID = FOOD_ITEMS.FOOD_ITEM_ID
LEFT JOIN ORDERS ON FOOD_ITEMS_ORDERS.ORDER_ID = ORDERS.ORDER_ID
LEFT JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID;

INSERT INTO FOOD_ITEMS_ORDERS (FOOD_ITEM_ID, ORDER_ID) VALUES (:FOOD_ITEM_ID, :ORDER_ID);

UPDATE FOOD_ITEMS_ORDERS SET FOOD_ITEM_ID=:FOOD_ITEM_ID, ORDER_ID=:ORDER_ID WHERE FOOD_ITEM_ID=:FOOD_ITEM_ID;
UPDATE FOOD_ITEMS_ORDERS SET FOOD_ITEM_ID=:FOOD_ITEM_ID, ORDER_ID=:ORDER_ID WHERE ORDER_ID=:ORDER_ID;

-- Since the relationship requires a join, deleting a food item
-- deletes all orders depending on/containing that food item
-- deleting from FOOD_ITEMS_ORDERS is handled by the cascade,
-- but since ORDERS is not directly related to FOOD_ITEMS,
-- deleting from ORDERS happens explicitly when a FOOD_ITEM is deleted
-- if that ORDER contains that food item

-- Deleting a FOOD_ITEM results in deleting that item from FOOD_ITEMS_ORDERS by CASCADE
-- and explicitly from the ORDERS table via a JOIN involving the intersection table.
-- Citation for the syntax for the DELETE with JOIN. Date: 3/7/2026
-- Developed with reference to:
-- Source URL: https://stackoverflow.com/questions/2763206/deleting-rows-with-mysql-left-join
DELETE `FOOD_ITEMS_ORDERS`, `ORDERS` FROM ORDERS
    LEFT JOIN FOOD_ITEMS_ORDERS ON FOOD_ITEMS_ORDERS.ORDER_ID = ORDERS.ORDER_ID
    WHERE FOOD_ITEMS_ORDERS.FOOD_ITEM_ID = :FOOD_ITEM_ID_FROM_FORM;