-- The following is original work.
SELECT F.FLOWER_ID, FB.BOUQUET_ID, C.COLOR, F.NAME, F.MEANING FROM FLOWERS AS F
LEFT JOIN FLOWERS_BOUQUETS AS FB ON F.FLOWER_ID = FB.FLOWER_ID
LEFT JOIN COLORS AS C ON F.COLOR_ID = C.COLOR_ID;
