-- This work is original
SELECT FB.BOUQUET_ID, B.NAME AS BOUQUET, B.DESCRIPTION,
       F.FLOWER_ID, F.NAME as FLOWER,
       CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
       CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM FLOWERS_BOUQUETS AS FB
LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY BOUQUET_ID;