-- This work is original
SELECT B.BOUQUET_ID, B.NAME AS BOUQUET, B.DESCRIPTION,
    CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
    CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM BOUQUETS AS B
    LEFT JOIN FLOWERS_BOUQUETS AS FB ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
    LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY B.BOUQUET_ID;