-- This work is original
SELECT B.BOUQUET_ID AS NUMBER, B.NAME AS BOUQUET, B.DESCRIPTION,
    CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
    CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM BOUQUETS AS B
    LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
    LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY B.BOUQUET_ID;


