-- This work is original
SELECT O.ORDER_ID AS NUMBER, O.ORDER_DATE AS DATE, CONCAT(TRIM(C.FIRST_NAME), ' ', TRIM(C.LAST_NAME)) AS CUSTOMER,
R.NAME AS RESTAURANT, FI.NAME AS FOOD, FI.PRICE AS PRICE, O.TOTAL_PRICE AS TOTAL
FROM ORDERS AS O
LEFT JOIN FOOD_ITEMS_ORDERS AS FIO
ON O.ORDER_ID = FIO.ORDER_ID
LEFT JOIN FOOD_ITEMS AS FI
ON FIO.FOOD_ITEM_ID = FI.FOOD_ITEM_ID
LEFT JOIN RESTAURANTS AS R
ON FI.RESTAURANT_ID = R.RESTAURANT_ID
LEFT JOIN CUSTOMERS AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
ORDER BY CUSTOMER, O.ORDER_ID;
