SELECT CONCAT(TRIM(M.FNAME), ' ', TRIM(M.LNAME)) AS MAKER,
    B.NAME AS BOUQUET, FB.BOUQUET_ID, FB.FLOWER_ID, F.NAME AS FLOWER,
    C.COLOR,
    CONCAT(TRIM(R.FNAME), ' ', TRIM(R.LNAME)) AS RECIPIENT
FROM FLOWERS_BOUQUETS AS FB
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN MAKERS AS M ON M.MAKER_ID = B.MAKER_ID
    LEFT JOIN COLORS AS C ON C.COLOR_ID = F.COLOR_ID
    LEFT JOIN RECIPIENTS AS R ON R.RECIPIENT_ID = B.RECIPIENT_ID
ORDER BY FB.BOUQUET_ID, FB.FLOWER_ID;