SELECT CONCAT(TRIM(C.FIRST_NAME), ' ', TRIM(C.LAST_NAME)) AS CUSTOMER,
    FIO.ORDER_ID, FIO.FOOD_ITEM_ID, FI.NAME AS FOOD, R.NAME AS RESTAURANT
FROM FOOD_ITEMS_ORDERS AS FIO
    LEFT JOIN FOOD_ITEMS AS FI ON FIO.FOOD_ITEM_ID = FI.FOOD_ITEM_ID
    LEFT JOIN RESTAURANTS AS R ON R.RESTAURANT_ID = FI.RESTAURANT_ID
    LEFT JOIN ORDERS AS O ON O.ORDER_ID = FIO.ORDER_ID
    LEFT JOIN CUSTOMERS AS C ON C.CUSTOMER_ID = O.CUSTOMER_ID
ORDER BY FIO.ORDER_ID;