-- This work is original
SELECT CONCAT(TRIM(C.COLOR), ' ', TRIM(F.NAME)) AS FLOWER,
    FB.FLOWER_ID, B.BOUQUET_ID, B.NAME AS BOUQUET
FROM FLOWERS_BOUQUETS AS FB
    LEFT JOIN BOUQUETS AS B ON FB.BOUQUET_ID = B.BOUQUET_ID
    LEFT JOIN FLOWERS AS F ON FB.FLOWER_ID = F.FLOWER_ID
    LEFT JOIN COLORS AS C ON C.COLOR_ID = F.COLOR_ID
ORDER BY B.BOUQUET_ID;
